version: '3'
services:
  citadel:
    build: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=citadel
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=citadel
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose